module.exports = Object.assign({},
  require("./alignment"),
  require("./bg"),
  require("./borders"),
  require("./content"),
  require("./cursor"),
  require("./display"),
  require("./flex"),
  require("./fx"),
  require("./margins"),
  require("./padding"),
  require("./positioning"),
  require("./scrolling"),
  require("./sizing"),
  require("./text.js")
);