const params = require("../params.js");
module.exports = {};


// ".text-align-center": ["text-align:center"],
//   ".text-align-left": ["text-align:left"],
//   ".text-align-right": ["text-align:right"],
//   ".text-case-lower": ["text-transform:lowercase"],
//   ".text-case-title": ["text-transform:capitalize"],
//   ".text-case-upper": ["text-transform:uppercase"],
//   ".text-color-black": ["color:${color.black}"],
//   ".text-color-danger": ["color:${color.red}"],
//   ".text-color-grey-extra-l": ["color:${color.grey-light-at-50}"],
//   ".text-color-grey-l": ["color:${color.grey-light}"],
//   ".text-color-grey": ["color:${color.grey}"],
//   ".text-color-info": ["color:${color.blue}"],
//   ".text-color-primary-l": ["color:${color.blue-light}"],
//   ".text-color-primary": ["color:${color.blue}"],
//   ".text-color-secondary": ["color:${color.blue-dark}"],
//   ".text-color-success": ["color:${color.green}"],
//   ".text-color-warn": ["color:${color.yellow}"],
//   ".text-color-white": ["color:${color.white}"],
//   ".text-font-monospace": ["font-family:monospace"],
//   ".text-font-bold-italic": [
//     "font-family:${font.open-sans-bold-italic}, Arial",
//     "font-style:italic"
//   ],
//   ".text-font-bold": ["font-family:${font.open-sans-bold}, Arial"],
//   ".text-font-semi-bold": ["font-family:${font.open-sans-semi-bold}, Arial"],
//   ".text-font-semi-bold-italic": [
//     "font-family:${font.open-sans-semi-bold-italic}, Arial"
//   ],
//   ".text-font-italic": [
//     "font-family:${font.open-sans-italic}, Arial",
//     "font-style:italic"
//   ],
//   ".text-font": ["font-family:${font.open-sans}, Arial"],
//   ".text-font-l": ["font-family:${font.open-sans-light}, Arial"],
//   ".text-height-l": ["line-height:3.2${unit.base}"],
//   ".text-height-m": ["line-height:2.4${unit.base}"],
//   ".text-height-s": ["line-height:2.0${unit.base}"],
//   ".text-height-xl": ["line-height:4${unit.base}"],
//   ".text-height-xs": ["line-height:1.6${unit.base}"],
//   ".text-height-xxl": ["line-height:5${unit.base}"],
//   ".text-indent-l": ["text-indent:2${unit.base}"],
//   ".text-indent-m": ["text-indent:1.5${unit.base}"],
//   ".text-indent-s": ["text-indent:1.4${unit.base}"],
//   ".text-indent-xl": ["text-indent:2.5${unit.base}"],
//   ".text-indent-xs": ["text-indent:.5${unit.base}"],
//   ".text-nowrap": ["white-space:nowrap"],
//   ".text-preformat": ["white-space: pre"],
//   ".text-size-l": ["font-size:2.0${unit.base}"],
//   ".text-size-m": ["font-size:1.4${unit.base}"],
//   ".text-size-s": ["font-size:1.3${unit.base}"],
//   ".text-size-xl": ["font-size:2.4${unit.base}"],
//   ".text-size-xs": ["font-size:1.1${unit.base}"],
//   ".text-size-xxl": ["font-size:4${unit.base}"],
//   ".text-space-s": ["letter-spacing:0.1${unit.base}"],
//   ".text-space-xs": ["letter-spacing:0${unit.base}"],
//   ".text-underline-none": ["text-decoration:none"],
//   ".text-weight-normal": ["font-weight:normal"],