module.exports = Object.assign({},
  require("./boxes"),
  require("./buttons"),
  require("./cards"),
  require("./columns"),
  require("./forms"),
  require("./headers"),
  require("./indicators"),
  require("./links"),
  require("./lists"),
  require("./messaging"),
  require("./modals"),
  require("./navigations"),
  require("./tooltips"),
  require("./tables"),
  require("./tabs"),
  require("./typography")
);